services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx-proxy/custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${MOUNT_SSD_PATH}/nginxproxy/certs:/etc/nginx/certs
      - ${MOUNT_SSD_PATH}/nginxproxy/vhost.d:/etc/nginx/vhost.d
      - ${MOUNT_SSD_PATH}/nginxproxy/html:/usr/share/nginx/html
    networks:
      - mediacenter_network
      - immich_network_frontend

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=jellyfin.mediacenter.lan
      - VIRTUAL_PORT=8096
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 7359:7359/udp
    volumes:
      - ${MOUNT_SSD_PATH}/jellyfin/config:/config
      - ${MOUNT_SSD_PATH}/jellyfin/cache:/cache
      - ${MOUNT_SSD_PATH}/jellyfin/transcode:/transcode
      - ${MOUNT_HDD_PATH}/Media:/media
    networks:
      - mediacenter_network

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=transmission.mediacenter.lan
      - VIRTUAL_PORT=9091
      - PUID=1000
      - PGID=1000
    ports:
      - 51413:51413
    volumes:
      - ${MOUNT_SSD_PATH}/transmission:/config
      - ${MOUNT_HDD_PATH}/Downloads:/data/downloads
    networks:
      - mediacenter_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=sonarr.mediacenter.lan
      - VIRTUAL_PORT=8989
      - PUID=1000
      - PGID=1000
    volumes:
      - ${MOUNT_SSD_PATH}/sonarr:/config
      - ${MOUNT_HDD_PATH}/Media:/data/Media
      - ${MOUNT_HDD_PATH}/Downloads:/data/Downloads
    networks:
      - mediacenter_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=radarr.mediacenter.lan
      - VIRTUAL_PORT=7878
      - PUID=1000
      - PGID=1000
    volumes:
      - ${MOUNT_SSD_PATH}/radarr:/config 
      - ${MOUNT_HDD_PATH}/Media:/data/Media
      - ${MOUNT_HDD_PATH}/Downloads:/data/Downloads
    networks:
      - mediacenter_network

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=immich.mediacenter.lan
      - VIRTUAL_PORT=2283
    env_file:
      - .env
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - ${PHOTO_ARCHIVE_PATH}:/mnt/archive-photos:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    networks:
      - immich_network_frontend
      - immich_network_backend

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${MOUNT_SSD_PATH}/immich/model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: false
    networks:
      - immich_network_backend

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich_network_backend

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${MOUNT_SSD_PATH}/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      disable: false
    networks:
      - immich_network_backend

networks:
  mediacenter_network:
    driver: bridge
  immich_network_frontend:
    driver: bridge
  immich_network_backend:
    driver: bridge